Disable volume plugin.
Because it breaks in my machine:

❯ env CNX_MACHINE="laptop" /nix/store/1bpqzr8rpqh9y2i5y5sif7ig9q3rgdls-cnx-sibi-0.1/bin/cnx-sibi
ALSA lib control.c:1543:(snd_ctl_open_conf) Either /nix/store/rd291976ng8b7ajj09z4zxchd8bknm71-alsa-plugins-1.2.7.1/lib/alsa-lib/libasound_module_ctl_pulse.so cannot be opened or _snd_ctl_pulse_open was not defined inside
Error: Failed to open ALSA mixer: default

Caused by:
    0: ALSA function 'snd_mixer_attach' failed with error 'ENXIO: No such device or address'
    1: ENXIO: No such device or address